export const INCIDENT_STATES = {
  CREATED: "CREATED",
  ANALYZING: "ANALYZING",
  READY: "READY",
  HOSPITAL_SELECTED: "HOSPITAL_SELECTED",
  AMBULANCE_REQUESTED: "AMBULANCE_REQUESTED",
  AMBULANCE_ASSIGNED: "AMBULANCE_ASSIGNED",
  AMBULANCE_ACCEPTED: "AMBULANCE_ACCEPTED",
  EN_ROUTE: "EN_ROUTE",
  HOSPITAL_ACCEPTED: "HOSPITAL_ACCEPTED",
  HOSPITAL_READY: "HOSPITAL_READY",
  ARRIVED: "ARRIVED",
  RESOLVED: "RESOLVED",
  CANCELLED: "CANCELLED",
  REJECTED: "REJECTED",
  TIMEOUT: "TIMEOUT",
  NO_AMBULANCE: "NO_AMBULANCE",
  HOSPITAL_UNAVAILABLE: "HOSPITAL_UNAVAILABLE",
};

export const ALLOWED_TRANSITIONS = {
  [INCIDENT_STATES.CREATED]: [INCIDENT_STATES.ANALYZING, INCIDENT_STATES.CANCELLED],
  [INCIDENT_STATES.ANALYZING]: [INCIDENT_STATES.READY, INCIDENT_STATES.CANCELLED, INCIDENT_STATES.REJECTED, INCIDENT_STATES.TIMEOUT],
  [INCIDENT_STATES.READY]: [INCIDENT_STATES.HOSPITAL_SELECTED, INCIDENT_STATES.AMBULANCE_REQUESTED, INCIDENT_STATES.CANCELLED, INCIDENT_STATES.TIMEOUT],
  [INCIDENT_STATES.HOSPITAL_SELECTED]: [INCIDENT_STATES.AMBULANCE_REQUESTED, INCIDENT_STATES.CANCELLED, INCIDENT_STATES.HOSPITAL_UNAVAILABLE],
  [INCIDENT_STATES.AMBULANCE_REQUESTED]: [
    INCIDENT_STATES.AMBULANCE_ASSIGNED,
    INCIDENT_STATES.AMBULANCE_ACCEPTED,
    INCIDENT_STATES.EN_ROUTE,
    INCIDENT_STATES.ARRIVED,
    INCIDENT_STATES.RESOLVED,
    INCIDENT_STATES.NO_AMBULANCE,
    INCIDENT_STATES.CANCELLED,
    INCIDENT_STATES.TIMEOUT,
  ],
  [INCIDENT_STATES.AMBULANCE_ASSIGNED]: [
    INCIDENT_STATES.AMBULANCE_ACCEPTED,
    INCIDENT_STATES.EN_ROUTE,
    INCIDENT_STATES.ARRIVED,
    INCIDENT_STATES.RESOLVED,
    INCIDENT_STATES.REJECTED,
    INCIDENT_STATES.TIMEOUT,
    INCIDENT_STATES.CANCELLED,
  ],
  [INCIDENT_STATES.AMBULANCE_ACCEPTED]: [
    INCIDENT_STATES.EN_ROUTE,
    INCIDENT_STATES.ARRIVED,
    INCIDENT_STATES.RESOLVED,
    INCIDENT_STATES.CANCELLED,
  ],
  [INCIDENT_STATES.EN_ROUTE]: [
    INCIDENT_STATES.HOSPITAL_ACCEPTED,
    INCIDENT_STATES.ARRIVED,
    INCIDENT_STATES.RESOLVED,
    INCIDENT_STATES.CANCELLED,
  ],
  [INCIDENT_STATES.HOSPITAL_ACCEPTED]: [
    INCIDENT_STATES.HOSPITAL_READY,
    INCIDENT_STATES.ARRIVED,
    INCIDENT_STATES.RESOLVED,
    INCIDENT_STATES.CANCELLED,
  ],
  [INCIDENT_STATES.HOSPITAL_READY]: [
    INCIDENT_STATES.ARRIVED,
    INCIDENT_STATES.RESOLVED,
    INCIDENT_STATES.CANCELLED,
  ],
  [INCIDENT_STATES.ARRIVED]: [
    INCIDENT_STATES.EN_ROUTE,
    INCIDENT_STATES.RESOLVED,
    INCIDENT_STATES.CANCELLED,
  ],
};

export const TERMINAL_STATES = new Set([
  INCIDENT_STATES.RESOLVED,
  INCIDENT_STATES.CANCELLED,
  INCIDENT_STATES.REJECTED,
  INCIDENT_STATES.TIMEOUT,
  INCIDENT_STATES.NO_AMBULANCE,
  INCIDENT_STATES.HOSPITAL_UNAVAILABLE,
]);

export const canTransitionTo = (fromStatus, toStatus) => {
  const allowed = ALLOWED_TRANSITIONS[fromStatus] || [];
  return allowed.includes(toStatus);
};

export const getStateTransitionError = (fromStatus, toStatus) => {
  if (!canTransitionTo(fromStatus, toStatus)) {
    return {
      statusCode: 409,
      code: "INVALID_TRANSITION",
      message: `Invalid transition from ${fromStatus} to ${toStatus}`,
    };
  }

  return null;
};
