export const EMERGENCY_STATES = Object.freeze({
  USER_REQUESTED: "USER_REQUESTED",
  HOSPITAL_SELECTED: "HOSPITAL_SELECTED",
  AMBULANCE_ASSIGNED: "AMBULANCE_ASSIGNED",
  AMBULANCE_ACCEPTED: "AMBULANCE_ACCEPTED",
  AMBULANCE_EN_ROUTE_TO_USER: "AMBULANCE_EN_ROUTE_TO_USER",
  AMBULANCE_ARRIVED: "AMBULANCE_ARRIVED",
  OTP_VERIFIED: "OTP_VERIFIED",
  PATIENT_PICKED_UP: "PATIENT_PICKED_UP",
  EN_ROUTE_TO_HOSPITAL: "EN_ROUTE_TO_HOSPITAL",
  ARRIVED_AT_HOSPITAL: "ARRIVED_AT_HOSPITAL",
  EMERGENCY_COMPLETED: "EMERGENCY_COMPLETED",
  CANCELLED: "CANCELLED",
});

export const TERMINAL_EMERGENCY_STATES = Object.freeze([
  EMERGENCY_STATES.EMERGENCY_COMPLETED,
  EMERGENCY_STATES.CANCELLED,
]);
